### ISSUE TITLE
Icono para el lanzador

### ISSUE THREAD

**Issue by FerCasRey** [FerCasRey/DHYMFer#2]
Necesitamos un icono para el lanzador, para poder verlo en el escritorio, por ejemplo.

Cualquier idea es bienvenida, pero el trabajo final será de nuestro artista.

**Comment by G4rk0** [comment]
La primera versión del launcher está finalizada

**Comment by FerCasRey** [comment]
![image](https://github.com/FerCasRey/DHYMFer/assets/113211140/3bb57e1d-6516-4faa-9e55-17412646f5f5)


El icono esta bien, pero vamos a necesitar uno que se ajuste un poco mejor
