### ISSUE TITLE
Space Invaders

### ISSUE THREAD

**Issue by Yoelcanarion** [FerCasRey/DHYMFer#3]
Los enemigos desaparecen solos, al lanzar un proyectil con el espacio se resta una vida, superposición de enemigos.

**Comment by FerCasRey** [comment]
El juego no se  abre debido a las rutas de la imágenes usadas. Tendríamos que pensar en empezar a organizar el código para comprimir todo en una carpeta como única unidad de descarga.

**Comment by FerCasRey** [comment]
Todos los problemas han sido arreglados, excepto la superposición de enemigos. 

Cierro issue y abro otra para mayor limpieza.
